INSERT INTO HEALTH_PROFILE (USERNAME) VALUES ('paul');
INSERT INTO HEALTH_PROFILE (USERNAME) VALUES ('yvette');

INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID)
VALUES (60, 'HEART_RATE', (SELECT ID FROM HEALTH_PROFILE WHERE USERNAME = 'paul'));

INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID)
VALUES (98, 'BLOOD_OXYGEN_LEVEL', (SELECT ID FROM HEALTH_PROFILE WHERE USERNAME = 'yvette'));
