INSERT INTO HEALTH_PROFILE (USERNAME) VALUES ('admin');
INSERT INTO HEALTH_PROFILE (USERNAME) VALUES ('john');
/* HEART_RATE, ECG, BP_DIASTOLIC, BP_SYSTOLIC, BLOOD_OXYGEN_LEVEL */
INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID) VALUES (60, 'HEART_RATE', (select id from HEALTH_PROFILE where username = 'john'));
INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID) VALUES (80, 'ECG', (select id from HEALTH_PROFILE where username = 'john'));
INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID) VALUES (120, 'BP_SYSTOLIC', (select id from HEALTH_PROFILE where username = 'john'));
INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID) VALUES (80, 'BP_DIASTOLIC', (select id from HEALTH_PROFILE where username = 'john'));
INSERT INTO HEALTH_METRIC (VALUE, TYPE, PROFILE_ID) VALUES (97, 'BLOOD_OXYGEN_LEVEL', (select id from HEALTH_PROFILE where username = 'john'));
